# task configuration
check_regex: True
check_single_directory: False
compare_two_directories: False
remove_duplicates: False

# file name configuration
target_dir: /atlas/u/jihyeonlee/handlabeling/delta-1/nina
source_dir: /atlas/u/jihyeonlee/handlabeling/delta-1/jihyeon
dedupped_dir: /atlas/u/tajwar/dedupped_datasets/negative/

# regex
regex: /atlas/u/mhelabd/data/kiln-scaling/labelled_bangladesh_2019_2020/negative/**/*.hdf5

# size of each chunk
chunk_size: 0
