# task configuration
check_single_regex: True
check_double_regex: False

# file name configuration
target_regex: /atlas/u/tajwar/dedupped_datasets/positives_dedupped/**/*.hdf5
source_regex: /atlas/u/tajwar/dedupped_datasets/delta+1/**/*.hdf5
dedupped_dir: /atlas/u/tajwar/dedupped_datasets/conflict_resolved/delta+1/

# regex
regex:  /atlas/u/mhelabd/handlabeling_conflicts/no_conflicts/**/delta+1*.hdf5

# size of each chunk
chunk_size: 0
