# task configuration
check_regex: True
check_single_directory: False
compare_two_directories: False
remove_duplicates: False

# file name configuration
# target_dir: /atlas/u/jihyeonlee/handlabeling/delta-1/nina
# source_dir: /atlas/u/jihyeonlee/handlabeling/delta-1/jihyeon
dedupped_dir: /atlas/u/tajwar/dedupped_datasets/delta-1/

# regex
regex: /atlas/u/tajwar/data_files/no_conflicts/delta-1/**/*.hdf5

# size of each chunk
chunk_size: 0
