# task configuration
check_single_regex: True
check_double_regex: False

# file name configuration
# target_dir: /atlas/u/jihyeonlee/handlabeling/delta-1/nina
# source_dir: /atlas/u/jihyeonlee/handlabeling/delta-1/jihyeon
dedupped_dir: /atlas/u/tajwar/dedupped_datasets/positives/

# regex
regex: /atlas/u/tajwar/data_files/no_conflicts/positives/**/*.hdf5

# size of each chunk
chunk_size: 0
