# task configuration
check_single_regex: False
check_double_regex: True

# file name configuration
target_dir: /atlas/u/tajwar/dedupped_datasets/positives/
source_dir: /atlas/u/tajwar/dedupped_datasets/delta+1/
dedupped_dir: /atlas/u/tajwar/dedupped_datasets/positives_dedupped/

# regex
regex: /atlas/u/tajwar/data_files/no_conflicts/positives/**/*.hdf5

# size of each chunk
chunk_size: 0
