neg_regex: /atlas/u/tajwar/dedupped_datasets/negative/**/task_0.hdf5
pos_regex: /atlas/u/tajwar/dedupped_datasets/conflict_resolved/positives/**/task_0.hdf5
save_dir: /atlas/u/tajwar/dedupped_datasets/handlabelling_tasks/

negative_samples: 500
positive_samples: 50

chunk_size: 550
